#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanTimeDirectories
cleanAdiosOutput
cleanAuxiliary
cleanDynamicCode
cleanOptimisation
cleanPostProcessing
rm -rf processor*/
rm -rf logs/
rm -rf 0
rm -rf constant/polyMesh

# cleanCase0

#------------------------------------------------------------------------------
